name: Open Issue Workflow

on:
  issues: 
    types: [ labeled ]

jobs:
  job:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'mirror-issue' }}
    steps:
    - name: Open new issue on the public repository
      env:
        GH_TOKEN: ${{ secrets.GITHUB_MIRROR_TOKEN }}
        THIS_REPO: ${{ github.repository }}
        THIS_ISSUE: ${{ github.event.issue.number }}
        THIS_ISSUE_TITLE: ${{ github.event.issue.title }}
        THIS_ISSUE_BODY: ${{ github.event.issue.body }}
        OTHER_REPO: ${{ vars.OTHER_REPO }}
        LABELS: in-game-report
      run: |
          gh issue create --title "$THIS_ISSUE_TITLE" --label "$LABELS" --body "$THIS_ISSUE_BODY" --repo "$OTHER_REPO"
          gh issue close --repo "$THIS_REPO" --comment "Mirrored to main repository!" "$THIS_ISSUE"
